### ISSUE TITLE
나눔바른고딕 라이트 글씨 깨지는 현상('호')

### ISSUE THREAD

**Issue by imki123** [moonspam/NanumBarunGothic#1]
나눔바른고딕라이트를 썼을 때 모바일(삼성인터넷)에서 한글 '호'가 깨지는 현상이 나타나요.
호의 위쪽 가로획 두개가 색상이 회색으로 바뀌면서 글자가 제대로 보이지 않네요..
핸드폰 두대로 테스트 해봤는데 둘다 같은 증상이에요.
단, PC크롬에서 보면 이상없이 잘 나와요.
라이트가 깨져서 울트라 라이트로 바꿨더니 울트라 라이트는 깨지는 현상이 없네요.

**Comment by moonspam** [comment]
나눔 바른 고딕 최신 버전으로 다시 변환해서 올려보겠습니다!

**Comment by moonspam** [comment]
나눔 바른 고딕 버전을 1.1로 판올림했습니다.

https://cdn.jsdelivr.net/gh/moonspam/NanumBarunGothic@1.1/nanumbarungothicsubset.css 또는
https://cdn.jsdelivr.net/gh/moonspam/NanumBarunGothic@latest/nanumbarungothicsubset.css 로
적용해주세요!

노트8에서 삼성 인터넷(v10.2.00.53) 테스트한 결과 '호'가 잘 나오고 있습니다.
https://codepen.io/moonspam/pen/BaypbpE

CSS 변경 후에도 동일한 증상이 발생하는 경우, 폰트 크기나 색상 등 테스트 환경을 자세히 알려주시면 동일한 환경에서 다시 확인해 보겠습니다.
